services:
  tag-front:
    container_name: tag4me-front
    build:
      context: .
      dockerfile: Dockerfile
    image: jpth/tag4me
    restart: always
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/tag4me